language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mhan1029/docker-react -f Dockerfile.dev .

script:
  - docker run mhan1029/docker-react npm run test -- --coverage
